### ISSUE TITLE
Add api extractors for Google Vision and Speech APIs

### ISSUE THREAD

**Issue by tyarkoni** [tyarkoni/featureX#23]
A high priority (perhaps the highest?) for new extractors should be the Google [Cloud Vision API](https://cloud.google.com/vision/docs/) and [Cloud Speech API](https://cloud.google.com/speech/docs/). These will probably deliver much better performance than most of the other APIs we currently interface with or are considering. We may want to consider creating a separate module just for Google APIs, since they share a common Python interface (the [Google API Python client](https://developers.google.com/api-client-library/python/), which we can wrap).

**Comment by tyarkoni** [comment]
There's a nice worked example in [this gist](https://gist.github.com/dannguyen/a0b69c84ebc00c54c94d) that seems to do exactly what we want.

**Comment by satra** [comment]
here is another api-based feature extractor: https://github.com/douwekiela/mmfeat

**Comment by tyarkoni** [comment]
Featurex now supports the major Google Cloud Vision API endpoints thanks to #50. The Cloud Speech API still remains to be implemented, so I'll leave this open for now.

**Comment by tyarkoni** [comment]
Closing thanks to #54.
