### ISSUE TITLE
StimCollection class

### ISSUE THREAD

**Issue by tyarkoni** [tyarkoni/featureX#38]
At the moment the standard way to apply extractors to a `Stim` is via an `.extract` call to the `Stim`--e.g.,

```python
stim = ImageStim('my_image.jpg')
extractors = [ExtractorA(), ExtractorB(), ExtractorC()]
stim.extract(extractors)
```

This allows multiple Extractors to be applied at once to a single Stim, but it would be useful to do multiple stims at once. Some kind of StimCollection container that implicitly loops over Stims might be worth adding. Thoughts?

**Comment by ljchang** [comment]
This would be nice.  Also, if it had multiprocessing, so this could be easily parallelized.  A related question is about how we want to deal with features that could be applied to video and image stims.  Do we want to loop over all frames and treat them as images?

**Comment by tyarkoni** [comment]
Re: images vs videos: that's how it works right now, yes. You can iterate `VideoStims`, which gives you `VideoFrameStims` that are basically glorified images. This works okay, but definitely needs to be made more principled. Right now every extractor that can handle both needs to explicitly check for type and adjust accordingly. It's probably worth spending some time to come up with a cleaner interface (or at the very least, a helpful Mixin) that minimizes redundancy and imposes some standardization.

**Comment by tyarkoni** [comment]
Closing because we're moving to a scikit-learn-like API that expects most extraction calls to happen on the `Extractor` rather than the `Stim` (i.e., `extractor.transform()` rather than `stim.extract()`).
