### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by tyarkoni** [tyarkoni/featureX#43]
We now have working continuous integration testing via travis-ci; the coveralls report is [here](https://coveralls.io/github/tyarkoni/featureX?branch=master). We're not doing too badly, but we should be able to get to 95%+ coverage without too much work. Additionally, as a secondary priority, many of the earliest tests I wrote are overly broad, and could stand to be refactored.

**Comment by qmac** [comment]
I've begun to work on this, have a branch going with test additions: https://github.com/qmac/featureX/tree/tests-coverage

**Comment by tyarkoni** [comment]
Great! Will look at it when I can.

**Comment by tyarkoni** [comment]
We're doing pretty well on tests now, so I'm closing this.
