### ISSUE TITLE
add SRT support

### ISSUE THREAD

**Issue by tyarkoni** [tyarkoni/featureX#6]
It would be useful to support text feature extraction from subtitle files.

**Comment by shabtastic** [comment]
i found this tool: [psyrt](https://github.com/byroot/pysrt) -- is this the kind of thing you had in mind?

**Comment by tyarkoni** [comment]
This looks like it could be helpful. The main question is whether we would want to add it as a dependency, given that we probably don't need most of its functionality. It might be possible to adapt only the code that reads SRTs (assuming it exists). Otherwise we could roll our own.

**Comment by shabtastic** [comment]
thanks -- i'll see if i can figure out a reasonable way to use it. :)

**Comment by tyarkoni** [comment]
Closed in #25
